# ----------------------------------------
# Application Config
# ----------------------------------------
server:
 servlet:
  context-path: /api/v1/sesame
   
--- 
# ----------------------------------------
# REST PROPERTIES
# ----------------------------------------
spring:
 data:
  rest:
   defaultPageSize: 10
   maxPageSize: 100

---
# ----------------------------------------
# DB PROPERTIES
# ----------------------------------------
spring:
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sesame_db?useSSL=false
  username: root
  password: 1234

---
# ----------------------------------------
# JPA PROPERTIES
# ----------------------------------------
spring:
 jpa:
  hibernate:
   ddlAuto: update
   naming:
    physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  generate-ddl: true
  show-sql: true
  database: mysql
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  properties:
   hibernate:
    format_sql: true
    enableLazyLoadNoTrans: true
    id:
     newGeneratorMappings: false
